//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiceoCientifico.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoxMateria
    {
        public int IdAlumnoMateria { get; set; }
        public int IdAlumno { get; set; }
        public int IdMateria { get; set; }
        public Nullable<decimal> Bimestre1 { get; set; }
        public Nullable<decimal> Bimestre2 { get; set; }
        public Nullable<decimal> Bimestre3 { get; set; }
        public Nullable<decimal> Bimestre4 { get; set; }
        public string CicloEscolar { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
