//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiceoCientifico.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoXSeccion
    {
        public int IdAlumnoXSeccion { get; set; }
        public int IdAlumno { get; set; }
        public int IdSeccion { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
