//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiceoCientifico.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosxUsuario
    {
        public int IdPermisosxUsuario { get; set; }
        public int IdUsuario { get; set; }
        public int IdPermiso { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual Permisos Permisos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
